### ISSUE TITLE
Low BUSCO score on predicted geneset

### ISSUE THREAD

**Issue by pgonzale60** [FerriolCalvet/geneidBLASTx-nf#3]
Hi Ferriol!

I hope you're doing well. I recently tried out your gene prediction tool and wanted to give you some feedback. I found that the results were not as good as those obtained with more popular tools. In fact, the completeness of the gene predictions was only around 34%, compared to ~90% using other tools. 
I obtained the genemark and augustus scores from the genesets generated by the braker pipeline. For the protein mode I used Swissprot as reference. I ran geneidx with default parameters. It was very fast indeed. Do you know what could improve the results?

![gene predictions](https://user-images.githubusercontent.com/6851437/221836706-008234e2-8244-4876-9877-11d523897d82.png)

All the best,
Pablo

**Comment by pgonzale60** [comment]
Sorry, I forgot to specify which species I annotated. It is _Auanema rhodensis_. I am using an updated genome assembly but the number of gene prediction matches those previously reported for the [one assembled with Illumina](https://www.ncbi.nlm.nih.gov/assembly/GCA_947366455.1/).

**Comment by FerriolCalvet** [comment]
Hi Pablo,

Sorry for the late reply, I did not reply when I first saw the issue and I completely forgot.
Thank you for bringing this up. 
Most of our testing was done in vertebrates and insects where there are more pre-built parameter files and proteins shared over multiple species.
I also run it for some nematods, and I found that the behaviour was less stable with some species achieving good results and others with poorer performance. I suspect it could be due to a bigger distance between the species that was used to generate the parameter file and the species that you want to annotate.
I will download the assembly that you are linking here and try if I can figure out what could be happening. Apart from the parameter files and proteins there are other values that can be adjusted such as the weight of the coding probability or the weight of the splice sites scores among others. I will try it and get back to you ASAP.

In general, I would expect that geneidx performs a bit worse than BRAKER or other more complete programs, but it should be comparable to the other "simple" _ab initio_ programs.

Thank you again for using geneidx and I will let you know what changes you could make to improve the performance.

Ferriol
